/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.hms.view;

import com.hms.model.PathologicalTest;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author MD. Samir Al Fayed Ifti
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnlogout = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuHome = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        menupsearch = new javax.swing.JMenuItem();
        menupsetup = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menursearch = new javax.swing.JMenuItem();
        menursetup = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Welcome To Our Hospital Management Software: Shifa(Aroggo)!");

        btnlogout.setText("Log Out");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });

        menuHome.setText("Home");
        jMenuBar1.add(menuHome);

        jMenu4.setText("Medical Test");

        jMenu1.setText("Pathological Test");

        menupsearch.setText("Search");
        menupsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menupsearchActionPerformed(evt);
            }
        });
        jMenu1.add(menupsearch);

        menupsetup.setText("Setup(input)");
        menupsetup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menupsetupActionPerformed(evt);
            }
        });
        jMenu1.add(menupsetup);

        jMenu4.add(jMenu1);

        jMenu5.setText("Rdiological Test");

        menursearch.setText("Search");
        menursearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menursearchActionPerformed(evt);
            }
        });
        jMenu5.add(menursearch);

        menursetup.setText("Setup(input)");
        menursetup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menursetupActionPerformed(evt);
            }
        });
        jMenu5.add(menursetup);

        jMenu4.add(jMenu5);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
            .addComponent(btnlogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 293, Short.MAX_VALUE)
                .addComponent(btnlogout))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        // TODO add your handling code here:
            int response = JOptionPane.showConfirmDialog(this, "Are you sure you want to log out?", 
            "Logout Confirmation", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
    
    if (response == JOptionPane.YES_OPTION) {
        // Close the current window (Home JFrame)
        this.dispose();
        
        // Redirect to the login screen
        Login loginScreen = new Login();  // Assuming you have a Login JFrame class
        loginScreen.setVisible(true);
    }
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void menupsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menupsearchActionPerformed
         // TODO add your handling code here:
        new PathologicalTestSearch().setVisible(true);
    }//GEN-LAST:event_menupsearchActionPerformed

    private void menupsetupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menupsetupActionPerformed
        // TODO add your handling code here:
        new PathologicalTestSetup().setVisible(true);
    }//GEN-LAST:event_menupsetupActionPerformed

    private void menursearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menursearchActionPerformed
        // TODO add your handling code here:
        new RadiologicalTestSearch().setVisible(true);
    }//GEN-LAST:event_menursearchActionPerformed

    private void menursetupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menursetupActionPerformed
        // TODO add your handling code here:
        new RadiologicalTestSetup().setVisible(true);
    }//GEN-LAST:event_menursetupActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new home().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuHome;
    private javax.swing.JMenuItem menupsearch;
    private javax.swing.JMenuItem menupsetup;
    private javax.swing.JMenuItem menursearch;
    private javax.swing.JMenuItem menursetup;
    // End of variables declaration//GEN-END:variables

    private static class Login {

        public Login() {
        }

        private void setVisible(boolean b) {
           // throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }
    }
}
