/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.hms.view;

import com.hms.model.PathologicalTest;

/**
 *
 * @author samir
 */
public class PathologicalCostCalculation extends javax.swing.JFrame {

    private PathologicalTest test;

    /**
     * Creates new form PathologicalCostCalculation
     */
    public PathologicalCostCalculation() {
        initComponents();
        test = new PathologicalTest();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelCostOfSingleTest = new javax.swing.JLabel();
        txtCostOfSingleTest = new javax.swing.JTextField();
        labelNumberOfTests = new javax.swing.JLabel();
        txtNumberOfTests = new javax.swing.JTextField();
        labelDiscountPercentage = new javax.swing.JLabel();
        txtDiscountPercentage = new javax.swing.JTextField();
        labelTotalCost = new javax.swing.JLabel();
        txtTotalCost = new javax.swing.JTextField();
        btnTotalCost = new javax.swing.JButton();
        btnDiscountedCost = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pathological Cost Calculation");

        labelCostOfSingleTest.setText("Cost of a Single Test :");

        txtCostOfSingleTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCostOfSingleTestActionPerformed(evt);
            }
        });

        labelNumberOfTests.setText("Number of Tests :");

        txtNumberOfTests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumberOfTestsActionPerformed(evt);
            }
        });

        labelDiscountPercentage.setText("Discount Percentage :");

        txtDiscountPercentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiscountPercentageActionPerformed(evt);
            }
        });

        labelTotalCost.setText("Total Cost :");

        txtTotalCost.setEditable(false);
        txtTotalCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalCostActionPerformed(evt);
            }
        });

        btnTotalCost.setText("Total Cost");
        btnTotalCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalCostActionPerformed(evt);
            }
        });

        btnDiscountedCost.setText("Discounted Cost");
        btnDiscountedCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiscountedCostActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(labelTotalCost, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelDiscountPercentage, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                            .addComponent(labelNumberOfTests, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelCostOfSingleTest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCostOfSingleTest, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(txtNumberOfTests)
                            .addComponent(txtDiscountPercentage)
                            .addComponent(txtTotalCost)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(btnTotalCost, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135)
                        .addComponent(btnDiscountedCost))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(btnCancel)))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCostOfSingleTest)
                    .addComponent(txtCostOfSingleTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNumberOfTests)
                    .addComponent(txtNumberOfTests, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDiscountPercentage)
                    .addComponent(txtDiscountPercentage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTotalCost)
                    .addComponent(txtTotalCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTotalCost)
                    .addComponent(btnDiscountedCost))
                .addGap(34, 34, 34)
                .addComponent(btnCancel)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCostOfSingleTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCostOfSingleTestActionPerformed
        // TODO add your handling code here:
        String input = txtCostOfSingleTest.getText();
        if (!input.matches("\\d+(\\.\\d{1,2})?")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter a valid numerical value for the cost.");
            txtCostOfSingleTest.setText("");
        }
    }//GEN-LAST:event_txtCostOfSingleTestActionPerformed

    private void txtNumberOfTestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumberOfTestsActionPerformed
        // TODO add your handling code here:
        String input = txtNumberOfTests.getText();
        if (!input.matches("\\d+")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter a valid numerical value for the number of tests.");
            txtNumberOfTests.setText("");
        }
    }//GEN-LAST:event_txtNumberOfTestsActionPerformed

    private void txtDiscountPercentageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiscountPercentageActionPerformed
        // TODO add your handling code here:
        String input = txtDiscountPercentage.getText();
        if (!input.matches("\\d+(\\.\\d{1,2})?") || Double.parseDouble(input) > 100) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter a valid discount percentage (0-100).");
            txtDiscountPercentage.setText("");
        }
    }//GEN-LAST:event_txtDiscountPercentageActionPerformed

    private void txtTotalCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalCostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalCostActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnTotalCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalCostActionPerformed
        // TODO add your handling code here:
        try {
            double costOfSingleTest = Double.parseDouble(txtCostOfSingleTest.getText());
            int numberOfTests = Integer.parseInt(txtNumberOfTests.getText());

            double totalCost = costOfSingleTest * numberOfTests;
            txtTotalCost.setText(String.format("%.2f", totalCost));

            // Display the result in a dialog box
            javax.swing.JOptionPane.showMessageDialog(this, "Total Cost: $" + String.format("%.2f", totalCost));
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please ensure all inputs are valid numbers.");
        }
    }//GEN-LAST:event_btnTotalCostActionPerformed

    private void btnDiscountedCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiscountedCostActionPerformed
        // TODO add your handling code here:
        try {
            double costOfSingleTest = Double.parseDouble(txtCostOfSingleTest.getText());
            int numberOfTests = Integer.parseInt(txtNumberOfTests.getText());
            double discountPercentage = Double.parseDouble(txtDiscountPercentage.getText());

            double totalCost = costOfSingleTest * numberOfTests;
            double discountAmount = totalCost * (discountPercentage / 100);
            double discountedCost = totalCost - discountAmount;
            txtTotalCost.setText(String.format("%.2f", discountedCost));

            // Display the result in a dialog box
            javax.swing.JOptionPane.showMessageDialog(this, "Discounted Cost: $" + String.format("%.2f", discountedCost));
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please ensure all inputs are valid numbers.");
        }
    }//GEN-LAST:event_btnDiscountedCostActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PathologicalCostCalculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PathologicalCostCalculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PathologicalCostCalculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PathologicalCostCalculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PathologicalCostCalculation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDiscountedCost;
    private javax.swing.JButton btnTotalCost;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelCostOfSingleTest;
    private javax.swing.JLabel labelDiscountPercentage;
    private javax.swing.JLabel labelNumberOfTests;
    private javax.swing.JLabel labelTotalCost;
    private javax.swing.JTextField txtCostOfSingleTest;
    private javax.swing.JTextField txtDiscountPercentage;
    private javax.swing.JTextField txtNumberOfTests;
    private javax.swing.JTextField txtTotalCost;
    // End of variables declaration//GEN-END:variables
}
